### ISSUE TITLE
Google Slides, Docs implementation?

### ISSUE THREAD

**Issue by OllieSchwartz** [Etcetera-Type-Co/Trispace#6]
I just stumbled upon your beautiful font at Google Fonts. Do you have any information if or when the font will be available in G-Slides and G-Docs too? For now, I can't find or add it via the G-Slides Font-Browser for example.

**Comment by sursly** [comment]
Hey @OllieSchwartz! Unfortunately that's out of my control. There is an open issue here that addresses what you're asking (and someone posted a makeshift solution, which I haven't tried).

**Comment by sursly** [comment]
https://github.com/google/fonts/issues/2623
